language: python
python: 
- "3.6"

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntugis/ppa"
    packages:
      - gdal-bin
      - libgdal-dev

install:
  - pip install .

script:
  - pytest
