language: python
python: 
- "3.6"

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get install -y libgdal-dev
  - sudo apt-get install -y gdal-bin

install:
  - pip install .

script:
  - pytest
