language: python
python: 
- "3.6"

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntugis/ppa"
    packages:
      - gdal-bin
      - libgdal-dev

before_install:
  - gdal-config --version
  - pip install --global-option=build_ext --global-option="-I/usr/include/gdal" GDAL==`gdal-config --version`

install:
  - pip install .

script:
  - pytest
