language: python
python: 
- "3.6"

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntugis/ppa"
    packages:
      - gdal-bin
      - libgdal-dev

install:
  - python --version
  - pip --version
  - gdal-config --version
  - pip install --global-option=build_ext --global-option="-I/usr/include/gdal" GDAL==`gdal-config --version`
  - pip install .

script:
  - pytest
